#!/bin/sh

# File preview handler for lf.
# Delivered from Luke Smith


set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

# Note that the cache file name is a function of file information, meaning if
# an image appears in multiple places across the machine, it will not have to
# be regenerated once seen.

case "$(file --dereference --brief --mime-type -- "$1")" in
	text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1"  ;;
	text/troff) man ./ "$1" | col -b ;;
	text/* | */xml) bat --terminal-width "$4" -f "$1" ;;
	application/zip) atool --list -- "$1" ;;
        audio/* | application/octet-stream) mediainfo "$1" || exit 1;;
        */pdf)
		CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
		[ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		image "$CACHE.jpg" "$2" "$3" "$4" "$5"
		;;
        *opendocument*) odt2txt "$1" ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
esac
exit 1
