#!/bin/sh

BAT=/sys/class/power_supply/BAT0

capacity="$(cat "$BAT/capacity" 2>&1)"

ICON100=""
#ICON75=""
ICON50=""
#ICON25=""
#ICON15=""

#TBC

if [["$capacity = 100"]]
then
	RES="$ICON100/ $capacity";
else
	RES="$ICON50/ $capacity";
fi

printf RES
